---
packages:
 - scikit-learn
 - logging
 - jsonlib
 - pandas
 - nltk
 - openpyxl
 - tabulate
 - slackclient
 - requests
 - scipy
 - mock

GIT_TOKEN: e0ace9b78db36779a35ab9416602194387bb37a2
SLACK_BOT_TOKEN: xoxb-795814705207-788531806065-9dWeyIRqj2t1LSbICYnDkB01
